#pragma once

#include "NativeGameplayTags.h"

namespace AlsViewModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsLocomotionModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InWater)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gliding)
}

namespace AlsRotationModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Targeting)
}

namespace AlsStanceTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace AlsGaitTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace AlsOverlayModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sword)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hatchet)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PickAxe)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hammer)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spear)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dagger)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordTwoHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Throw)
}

namespace AlsLocomotionActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
}

namespace AlsGroundedEntryModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FromRoll)
}

namespace AlsInputActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockJumping)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockRolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockMoveInput)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OverlayAction)
}

namespace AlsCharacterStateTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeakAttack)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ComboAttack)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blocking)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parrying)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincibility)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PerfectDodge)
}

namespace AlsCombatTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NextComboAttack)
}